### ISSUE TITLE
Add PhantomJS to docker image that is used to for R package CI

### ISSUE THREAD

**Issue by waddella** [insightsengineering/ci-images#1]
See the `teal.devel` CI fail message

- [ ] rerun the `teal.devel` ci pipeline on `main` branch

**Comment by dinakar29** [comment]
Installed here: https://github.com/insightsengineering/ci-images/commit/5dcbb26ab1815b036ce99498ba48db0843b1f47d
Currently testing and verify.

**Comment by dinakar29** [comment]
Resolved in https://github.com/insightsengineering/ci-images/pull/6
