### ISSUE TITLE
Update `car` package version to 3.1-0

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/ci-images#57]
The current version of `car` causes a documentation error in `tern` due to an update to the parameters of `car::Anova` in version 3.1-0.

Update the version of `car` to the latest version to resolve this error.

**Comment by dinakar29** [comment]
We're moving to R 4.2.1 + BioC 3.15 for testing and dev this week, so a newer version of `car` will be installed on those images.

**Comment by dinakar29** [comment]
I believe this should be fixed in the new images, @edelarua
